### ISSUE TITLE
feat: yjs IndexedDB support

### ISSUE THREAD

**Issue by arnaudbzn** [pluv-io/pluv#357]
### Describe the feature you'd like to request

Support `[IndexedDB](https://github.com/yjs/y-indexeddb)` provider to support offline capabilities.

### Describe the solution you'd like to see

When creating a room, add the possibility to enable indexedDB storage.
When the client is disconnected, the user updates are kept in the indexedDB storage, and when the connection is up again, the updates are sent to the websocket server.

### Describe alternate solutions

No other quick solution.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by leedavidcs** [comment]
Thanks! I'll look into adding y-indexeddb support in the next few days.

**Comment by arnaudbzn** [comment]
Awesome!

**Comment by leedavidcs** [comment]
Update on this feature request:

I haven't been able to commit enough time into this as I would have liked. This is something that I am still looking into; however, will likely not come for another few days :frowning_face:.

**Comment by leedavidcs** [comment]
This will be part of the next release
