### ISSUE TITLE
feat: History storage

### ISSUE THREAD

**Issue by cestef** [pluv-io/pluv#471]
### Describe the feature you'd like to request

Just as in [`liveblocks`](https://github.com/liveblocks/liveblocks/blob/ce41e3cf240a646b744ae3a085d71d963156aff4/packages/liveblocks-core/src/room.ts#L112), provide an history that can be undone/redone, paused/unpaused.

### Describe the solution you'd like to see

Maybe some kind of addon or just a feature implemented into core

### Describe alternate solutions

None

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by leedavidcs** [comment]
Thanks for the feature request!

I'll take a look into supporting this sometime this week 👍.

**Comment by leedavidcs** [comment]
@cestef 

Apologies for the wait on this feature. I've been quite busy with other things lately :slightly_frowning_face:.

This functionality is completed within a PR now :point_up:. Once e2e testing has been added, this will be deployed in the next release (should be within this week).

**Comment by cestef** [comment]
Thank you so much for your hard work ! Is there something I can help with ? Documentation or something such ?

**Comment by leedavidcs** [comment]
This has landed in the latest release of @pluv/react. Documentation will be up before the end of the week: https://github.com/pluv-io/pluv/releases/tag/%40pluv%2Freact%400.12.0
